<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cart</name>
   <tag></tag>
   <elementGuidId>609146d1-f520-4b17-b898-79a58aeab9ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div/div[2]/header/div/div[3]/section/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div/div[2]/header/div/div[3]/section/a</value>
   </webElementProperties>
</WebElementEntity>
