<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Absolute_country</name>
   <tag></tag>
   <elementGuidId>2e0dd46c-8c19-4720-9c3e-ed8cf0fdf481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[1]/section/form/main/div[2]/div/section/div/fieldset/div/div/div/div/div/div/div[1]/div[2]/div/div[2]/ul/div[10]/div[2]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[1]/section/form/main/div[2]/div/section/div/fieldset/div/div/div/div/div/div/div[1]/div[2]/div/div[2]/ul/div[10]/div[2]/div/select</value>
   </webElementProperties>
</WebElementEntity>
