<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Absolute_City</name>
   <tag></tag>
   <elementGuidId>72aea0ef-b824-4e34-8f91-fa1cde5bff46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[1]/section/form/main/div[2]/div/section/div/fieldset/div/div/div/div/div/div/div[1]/div[1]/div/div/ul/div[7]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[1]/section/form/main/div[2]/div/section/div/fieldset/div/div/div/div/div/div/div[1]/div[1]/div/div/ul/div[7]/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
