<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>absolute_company</name>
   <tag></tag>
   <elementGuidId>fb79486f-e941-4580-b91d-5cb709584959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div/section/form/main/div[2]/div/section/div/fieldset/div/div/div/div/div/div/div[1]/div[1]/div/div/ul/div[4]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div/section/form/main/div[2]/div/section/div/fieldset/div/div/div/div/div/div/div[1]/div[1]/div/div/ul/div[4]/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
